version: 2.1

executors:
  android-flutter:
    docker:
      - image: cirrusci/flutter:latest
    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m"'
jobs:
  beta_deploy:
    executor: android-flutter
    steps:
      - checkout
#      - run: echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > key.jks
#      - run: echo "$PLAY_STORE_UPLOAD_KEY_INFO" | base64 --decode > android/key.properties
      - run: sudo gem update --system
      - run: sudo gem install bundler:2.3.0
      - run: bundle install
      - run: bundle exec fastlane tests

workflows:
  deploy:
    jobs:
      - beta_deploy:
          filters:
            branches:
              only: beta

